# -*- coding: utf-8 -*-
"""1er_choix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rys7W7HX8QfSBVhDD8dqJtD8spaB9cjE
"""

!pip install numpy scipy matplotlib librosa soundfile

import numpy as np
import matplotlib.pyplot as plt
import librosa
import librosa.display
import soundfile as sf
from scipy.signal import iirnotch, filtfilt
from google.colab import files



print(" Upload fichier audio bruité (kennedy_noisy.wav)")
uploaded = files.upload()

filename = list(uploaded.keys())[0]

signal, fs = librosa.load(filename, sr=None)

print(" Audio chargé")
print("Sampling rate =", fs, "Hz")
print("Durée =", len(signal)/fs, "secondes")



plt.figure(figsize=(12,6))

D = librosa.amplitude_to_db(np.abs(librosa.stft(signal)), ref=np.max)

librosa.display.specshow(D, sr=fs, x_axis='time', y_axis='hz')

plt.title("Spectrogramme du signal bruité")
plt.colorbar()
plt.show()



f0 = 1000
Q = 30

b, a = iirnotch(f0, Q, fs)

signal_notch = filtfilt(b, a, signal)

print(" Notch Filter appliqué")



plt.figure(figsize=(12,6))

D2 = librosa.amplitude_to_db(np.abs(librosa.stft(signal_notch)), ref=np.max)

librosa.display.specshow(D2, sr=fs, x_axis='time', y_axis='hz')

plt.title("Spectrogramme après Notch Filter")
plt.colorbar()
plt.show()



noise_sample = signal_notch[0:int(0.5*fs)]

noise_fft = np.abs(librosa.stft(noise_sample))

noise_mean = np.mean(noise_fft, axis=1)

print(" Bruit estimé")


S = librosa.stft(signal_notch)

magnitude = np.abs(S)
phase = np.angle(S)

clean_magnitude = magnitude - noise_mean[:, np.newaxis]

clean_magnitude = np.maximum(clean_magnitude, 0)

S_clean = clean_magnitude * np.exp(1j * phase)

signal_clean = librosa.istft(S_clean)

print(" Spectral Subtraction appliquée")



plt.figure(figsize=(12,6))

D3 = librosa.amplitude_to_db(np.abs(librosa.stft(signal_clean)), ref=np.max)

librosa.display.specshow(D3, sr=fs, x_axis='time', y_axis='hz')

plt.title("Spectrogramme du signal restauré")
plt.colorbar()
plt.show()



def compute_snr(signal, noise):
    return 10 * np.log10(np.sum(signal**2) / np.sum(noise**2))

noise_before = signal - signal_notch
noise_after = signal_notch - signal_clean

snr_before = compute_snr(signal_notch, noise_before)
snr_after = compute_snr(signal_clean, noise_after)

print("====================================")
print("SNR avant traitement =", round(snr_before,2), "dB")
print("SNR après traitement =", round(snr_after,2), "dB")
print("Gain SNR =", round(snr_after - snr_before,2), "dB")
print("====================================")



plt.figure(figsize=(12,6))

plt.subplot(3,1,1)
plt.plot(signal)
plt.title("Signal original bruité")

plt.subplot(3,1,2)
plt.plot(signal_notch)
plt.title("Après Notch Filter")

plt.subplot(3,1,3)
plt.plot(signal_clean)
plt.title("Signal restauré final")

plt.tight_layout()
plt.show()


sf.write("kennedy_clean.wav", signal_clean, fs)

print(" Fichier restauré sauvegardé : kennedy_clean.wav")

files.download("kennedy_clean.wav")

print(" Mission accomplie : signal restauré avec succès")